import {
  Wallet,
  DollarSign,
  Home,
  CreditCard,
  ShoppingBag,
  Plug,
  Shield,
  Utensils,
  Shirt,
  Film,
  Tv,
  TrendingUp,
  Landmark,
  PiggyBank,
  HeartPulse,
  Gift,
  Umbrella,
  Plane,
  Banknote,
} from "lucide-react";

export const categoryIconMap = {
  salary: DollarSign,
  "other income": Wallet,
  rent: Home,
  emi: CreditCard,
  groceries: ShoppingBag,
  utilities: Plug,
  insurance: Shield,
  "eating out": Utensils,
  shopping: Shirt,
  entertainment: Film,
  subscriptions: Tv,
  "sip/mutual funds": TrendingUp,
  "stocks/bonds": Landmark,
  "emergency fund": PiggyBank,
  "retirement fund": PiggyBank,
  "vacation fund": Plane,
  "car/bike insurance": Umbrella,
  "health check-up": HeartPulse,
  "festivals/gifts": Gift,
  other: Banknote,
};
